# -*- coding: utf-8 -*-
"""OK_Pneumonia_detect_3classes_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119gOGSjJeDZA3RX6h5d4SZpOfD0sPAjk

**1. Install dependencies**
"""

!pip install timm

"""**2. Link drive (for data)**"""

from google.colab import drive
drive.mount('/content/drive')

"""**3. Data processing** (do it only once)"""

import os
import shutil

def clean_data(dir_path):
  base_path = os.path.join(dir_path, 'PNEUMONIA')
  if not os.path.isdir(base_path):
    print(f"'{base_path}' not exist. PASS.")
    return
  # Create folders
  virus_folder = os.path.join(dir_path, 'PNEUMONIA_VIRUS')
  bact_folder = os.path.join(dir_path, 'PNEUMONIA_BACT')

  os.makedirs(virus_folder, exist_ok=True)
  os.makedirs(bact_folder, exist_ok=True)

  # Loop through files in base_path
  for filename in os.listdir(base_path):
      file_path = os.path.join(base_path, filename)

      # Check if it's a file and ends with .jpeg
      if os.path.isfile(file_path) and filename.endswith('.jpeg'):
          if '_virus_' in filename:
              shutil.move(file_path, os.path.join(virus_folder, filename))
          elif '_bacteria_' in filename:
              shutil.move(file_path, os.path.join(bact_folder, filename))
  print("Images successfully sorted into 'virus' and 'bact' folders.")

  # Count only files (not subfolders)
  file_count = len([f for f in os.listdir(base_path) if os.path.isfile(os.path.join(base_path, f))])

  if file_count < 2:
    shutil.rmtree(base_path)
    print(f"Deleted '{base_path}'.")
  else:
    print(f"WARNING: '{base_path}' still has some files.")

clean_data('/content/drive/MyDrive/EPITECH/DEV-810/chest_Xray/train')
#clean_data('/content/drive/MyDrive/EPITECH/DEV-810/chest_Xray/val')
clean_data('/content/drive/MyDrive/EPITECH/DEV-810/chest_Xray/test')

"""**4. Build the data loader**

**4.1. Data preprocessing**
"""

from torchvision import datasets, transforms

# Original images (no augmentation)
original_tfms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

# # Augmented images
# augmented_tfms = transforms.Compose([
#     transforms.RandomHorizontalFlip(p=0.5),
#     transforms.RandomRotation(degrees=10),
#     transforms.Resize((224, 224)),
#     transforms.ColorJitter(brightness=0.2, contrast=0.2),
#     transforms.ToTensor(),
#     transforms.Normalize(mean=[0.485, 0.456, 0.406],
#                          std=[0.229, 0.224, 0.225])
# ])

"""**4.2. Build the dataset**"""

# load image and build dataset
train_data_dir = '/content/drive/MyDrive/EPITECH/DEV-810/chest_Xray/train'
train_dataset = datasets.ImageFolder(root=train_data_dir, transform=original_tfms)
print(f"Total images in train dataset: {len(train_dataset)}")

# this val dataset is NOT balanced, it does not contain the data about Pneumonia Virus
# so we only use it for the last fine-tuning
val_data_dir = '/content/drive/MyDrive/EPITECH/DEV-810/chest_Xray/val'
val_dataset = datasets.ImageFolder(root=val_data_dir, transform=original_tfms)
print(f"Total images in val dataset: {len(val_dataset)}")

test_data_dir = '/content/drive/MyDrive/EPITECH/DEV-810/chest_Xray/test'
test_dataset = datasets.ImageFolder(root=test_data_dir, transform=original_tfms)
print(f"Total images in test dataset: {len(test_dataset)}")

"""**4.3. Data summalization**"""

from collections import Counter

# print dataset
def print_dataset(dataset):
  class_counts = Counter(dataset.targets)
  idx_to_class = {v: k for k, v in dataset.class_to_idx.items()}
  for class_idx, count in class_counts.items():
      print(f"{idx_to_class[class_idx]}: {count} images")

def print_subset(subset):
    # Get the original dataset and the subset indices
    dataset = subset.dataset
    indices = subset.indices

    # Get target labels using the indices
    targets = [dataset.targets[i] for i in indices]

    # Count occurrences of each class
    class_counts = Counter(targets)

    # Get class names
    idx_to_class = {v: k for k, v in dataset.class_to_idx.items()}

    # Print results
    for class_idx, count in class_counts.items():
        print(f"{idx_to_class[class_idx]}: {count} images")

    # Example assuming train_dataset stores image paths in dataset.samples
    for i in range(3):
        original_idx = indices[i]  # Index in the original dataset
        image_path, label = dataset.samples[original_idx]  # Access filename and label

        print(f"Sample {i+1}: {image_path} | Label: {label}")

import random
from collections import defaultdict
from torch.utils.data import Subset

def get_train_val_subsets(dataset, samples_per_class_train: int, samples_per_class_val: int):
    class_indices = defaultdict(list)

    # Build class-to-indices mapping
    for idx, (image_path, label) in enumerate(dataset.samples):
        class_indices[label].append(idx)

    # Ensure reproducibility
    random.seed(42)

    train_indices = []
    val_indices = []

    for class_label, indices in class_indices.items():
        total_required = samples_per_class_train + samples_per_class_val

        if len(indices) >= total_required:
            selected_indices = random.sample(indices, total_required)
            train_selected = selected_indices[:samples_per_class_train]
            val_selected = selected_indices[samples_per_class_train:]
        else:
            print(f"Warning: Class {class_label} has only {len(indices)} samples.")
            split_point = min(samples_per_class_train, len(indices))
            train_selected = indices[:split_point]
            val_selected = indices[split_point:]

        train_indices.extend(train_selected)
        val_indices.extend(val_selected)

    train_subset = Subset(dataset, train_indices)
    val_subset = Subset(dataset, val_indices)

    return train_subset, val_subset

"""**4.4. Data split**"""

########## Only used to determinate the best hyper-paramters
########## Use Kfold to build validation dataset from training dataset
from sklearn.model_selection import KFold
from torch.utils.data import Subset
from torch.utils.data import DataLoader

# Parameters
k = 10 # 10 is best
dataset_size = len(train_dataset)

kfold = KFold(n_splits=k, shuffle=True, random_state=42)

# Get the first split only (no loop needed)
train_idx, val_idx = next(iter(kfold.split(range(dataset_size))))

# Create subsets
train_subset = Subset(train_dataset, train_idx)
val_subset = Subset(train_dataset, val_idx)

# DataLoaders
train_data_loader = DataLoader(train_subset, batch_size=32, shuffle=True)
val_data_loader = DataLoader(val_subset, batch_size=32, shuffle=False)
######
test_data_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

print("-------------------")
print("Training data")
print_subset(train_subset)
print("-------------------")
print("Validation data")
print_subset(val_subset)
print("-------------------")
print("Testing data")
print_dataset(test_dataset)

# ########## ONLY FOR TESTING
# ########## Build validation dataset manually from training dataset
# from sklearn.model_selection import KFold
# from torch.utils.data import Subset
# from torch.utils.data import DataLoader

# # Create subsets
# train_subset, val_subset = get_train_val_subsets(train_dataset, 50, 20)
# test_subset, _ = get_train_val_subsets(test_dataset, 20, 0)

# # DataLoaders
# train_data_loader = DataLoader(train_subset, batch_size=8, shuffle=True)
# val_data_loader = DataLoader(val_subset, batch_size=8, shuffle=False)
# ######
# test_data_loader = DataLoader(test_subset, batch_size=16, shuffle=False)

# print("-------------------")
# print("Training data")
# print_subset(train_subset)
# print("-------------------")
# print("Validation data")
# print_subset(val_subset)
# print("-------------------")
# print("Testing data")
# print_subset(test_subset)

# ########## FOR THE LAST FINE-TUNING
# from torch.utils.data import ConcatDataset, DataLoader

# # DataLoaders
# combined_dataset = ConcatDataset([train_dataset, val_dataset])
# train_data_loader = DataLoader(combined_dataset, batch_size=32, shuffle=True)
# val_data_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
# ######
# test_data_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# print("-------------------")
# print("Training data")
# print_dataset(train_dataset)
# print("-------------------")
# print("Validation data")
# print_dataset(val_dataset)
# print("-------------------")
# print("Testing data")
# print_dataset(test_dataset)

"""**5. Training**

**5.1. Load pre-trained model**
"""

import torch
import timm

# Load EfficientNetV2 with pretrained weights
model = timm.create_model('tf_efficientnetv2_s', pretrained=True)

# Adjust classifier for 3 classes
num_classes = 3
model.classifier = torch.nn.Linear(model.classifier.in_features, num_classes)

"""**5.2. Fine-tune model**"""

import torch
import torch.optim as optim
import copy
import time
from tqdm import tqdm
import os

save_dir = '/content/drive/MyDrive/EPITECH/DEV-810/models/'  # For Google Drive
os.makedirs(save_dir, exist_ok=True)
save_path = os.path.join(save_dir, 'best_model_2c_v2s.pth')

# Hyperparameters
num_epochs = 10 #
patience = 3  # Number of epochs to wait for improvement in validation loss

criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)


# To track the best model and early stopping
best_val_loss = float('inf')
epochs_without_improvement = 0

# Train the model
for epoch in range(num_epochs):
    start_time = time.time()  # Start timing

    # Training phase
    model.train()
    train_loss = 0.0
    correct_train = 0
    total_train = 0

    for images, labels in tqdm(train_data_loader, desc=f"Training Epoch {epoch+1}/{num_epochs}", leave=False):
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()

    train_loss /= len(train_data_loader)
    train_accuracy = (correct_train / total_train) * 100

    # Validation phase
    model.eval()
    val_loss = 0.0
    correct_val = 0
    total_val = 0

    with torch.no_grad():
        for val_images, val_labels in tqdm(val_data_loader, desc=f"Validation Epoch {epoch+1}/{num_epochs}", leave=False):
            val_outputs = model(val_images)
            val_loss += criterion(val_outputs, val_labels).item()
            _, predicted = torch.max(val_outputs, 1)
            total_val += val_labels.size(0)
            correct_val += (predicted == val_labels).sum().item()

    val_loss /= len(val_data_loader)
    val_accuracy = (correct_val / total_val) * 100

    # End timing and calculate epoch duration
    epoch_duration = time.time() - start_time

    # Print statistics
    print(f"Epoch [{epoch+1}/{num_epochs}], "
          f"Train Loss: {train_loss:.4f}, Train Accuracy: {train_accuracy:.2f}%, "
          f"Validation Loss: {val_loss:.4f}, Validation Accuracy: {val_accuracy:.2f}%, "
          f"Epoch Time: {epoch_duration:.2f} seconds")

    # Early stopping and saving best model
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_without_improvement = 0
        torch.save(model.state_dict(), save_path)
        print(f"Best model updated and saved to: {save_path}")
    else:
        epochs_without_improvement += 1

    if epochs_without_improvement >= patience:
        print(f"Early stopping triggered after {epoch+1} epochs with no improvement.")
        break

# Load best model weights
model.load_state_dict(torch.load(save_path))

"""**6. Evaluate the fine-tuned model**"""

from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import torch
from tqdm import tqdm
import numpy as np
import seaborn as sns

def test_model(model, test_data_loader, criterion, num_classes, class_names=None):
    model.eval()
    test_loss = 0.0
    correct_test = 0
    total_test = 0

    all_labels = []
    all_preds = []
    all_probs = []

    with torch.no_grad():
        for test_images, test_labels in tqdm(test_data_loader, desc="Test data", leave=False):
            outputs = model(test_images)
            loss = criterion(outputs, test_labels)
            test_loss += loss.item()

            _, predicted = torch.max(outputs, 1)
            all_labels.extend(test_labels.cpu().numpy())
            all_preds.extend(predicted.cpu().numpy())

            probs = torch.softmax(outputs, dim=1)
            all_probs.extend(probs.cpu().numpy())

            total_test += test_labels.size(0)
            correct_test += (predicted == test_labels).sum().item()

    test_loss /= len(test_data_loader)
    test_accuracy = (correct_test / total_test) * 100

    # Metrics
    cm = confusion_matrix(all_labels, all_preds)
    precision = precision_score(all_labels, all_preds, average='macro')
    recall = recall_score(all_labels, all_preds, average='macro')
    f1 = f1_score(all_labels, all_preds, average='macro')

    try:
        if num_classes == 2:
            roc_auc = roc_auc_score(all_labels, np.array(all_probs)[:, 1])
        else:
            roc_auc = roc_auc_score(all_labels, all_probs, multi_class='ovr')
    except ValueError as e:
        roc_auc = None
        print(f"ROC AUC could not be calculated: {e}")

    # Display metrics
    print(f"Test Loss: {test_loss:.4f}")
    print(f"Test Accuracy: {test_accuracy:.2f}%")
    print(f"Precision (macro): {precision:.4f}")
    print(f"Recall (macro): {recall:.4f}")
    print(f"F1 Score (macro): {f1:.4f}")
    if roc_auc:
        print(f"ROC AUC (OvR): {roc_auc:.4f}")

    print("\nConfusion Matrix:")
    print(cm)

    # Plot Confusion Matrix
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.xlabel('Prédictions')
    plt.ylabel('Vérité réelle')
    plt.title('Matrice de confusion')
    plt.show()

    # ROC Curve plotting
    if num_classes == 2:
        fpr, tpr, thresholds = roc_curve(all_labels, [p[1] for p in all_probs])
        plt.figure()
        plt.plot(fpr, tpr, label=f"ROC curve (AUC = {roc_auc:.2f})")
        plt.plot([0, 1], [0, 1], 'k--')
        plt.xlabel("Taux de faux positifs")
        plt.ylabel("Taux de vrais positifs")
        plt.title("Courbe ROC")
        plt.legend(loc="lower right")
        plt.show()

    elif num_classes > 2:
        y_true_bin = label_binarize(all_labels, classes=list(range(num_classes)))
        all_probs_np = np.array(all_probs)

        plt.figure(figsize=(8, 6))
        for i in range(num_classes):
            fpr, tpr, _ = roc_curve(y_true_bin[:, i], all_probs_np[:, i])
            roc_auc_i = auc(fpr, tpr)
            class_label = class_names[i] if class_names else f"Classe {i}"
            plt.plot(fpr, tpr, label=f"{class_label} (AUC = {roc_auc_i:.2f})")

        plt.plot([0, 1], [0, 1], 'k--', label='Aléatoire')
        plt.xlabel('Taux de faux positifs')
        plt.ylabel('Taux de vrais positifs')
        plt.title('Courbes ROC (One-vs-Rest)')
        plt.legend(loc="lower right")
        plt.grid()
        plt.show()

    return {
        'loss': test_loss,
        'accuracy': test_accuracy,
        'precision': precision,
        'recall': recall,
        'f1_score': f1,
        'roc_auc': roc_auc,
        'confusion_matrix': cm
    }

model.load_state_dict(torch.load('/content/drive/MyDrive/EPITECH/DEV-810/models/ok_81_k10_best_model_3c_v2s.pth'))
print("Best model loaded")
#
criterion = torch.nn.CrossEntropyLoss()
metrics = test_model(model, test_data_loader, criterion, num_classes=3, class_names=['Normal', 'Pneumonie bact', 'Pneumonie virus'])